# See https://www.philschmid.de/fine-tune-embedding-model-for-rag

In [ ]:
# # Install Pytorch & other libraries
# !pip install "torch==2.1.2" tensorboard
 
# # Install Hugging Face libraries
# !pip install --upgrade \
#   "sentence-transformers>=3" \
#   "datasets==2.19.1"  \
#   "transformers==4.41.2" 
 
#set up to save the hugging face token
# !git config --global credential.helper store

In [1]:
from huggingface_hub import login
login(token="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", add_to_git_credential=True)  # ADD YOUR TOKEN HERE

/home/kperkins411/anaconda3/envs/p311/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Token is valid (permission: write).
Your token has been saved in your configured git credential helpers (store).
Your token has been saved to /home/kperkins411/.cache/huggingface/token
Login successful

In [3]:
matryoshka_dimensions = [768, 512] # Important: large to small
import torch
from sentence_transformers import SentenceTransformer
from sentence_transformers.evaluation import (
    InformationRetrievalEvaluator,
    SequentialEvaluator,
)
from sentence_transformers.util import cos_sim
from datasets import load_dataset, concatenate_datasets
 
model_id = "BAAI/bge-base-en-v1.5"  # Hugging Face model ID
 
# Load a model
model = SentenceTransformer(
    model_id, device="cuda:0" if torch.cuda.is_available() else "cpu"
)
 
# load test dataset
test_dataset = load_dataset("json", data_files="tst.json", split="train")
train_dataset = load_dataset("json", data_files="trn.json", split="train")
corpus_dataset = concatenate_datasets([train_dataset, test_dataset])
 
# Convert the datasets to dictionaries
corpus = dict(
    zip(corpus_dataset["id"], corpus_dataset["positive"])
)  # Our corpus (cid => document)
queries = dict(
    zip(test_dataset["id"], test_dataset["anchor"])
)  # Our queries (qid => question)
 
# Create a mapping of relevant document (1 in our case) for each query
relevant_docs = {}  # Query ID to relevant documents (qid => set([relevant_cids])
for q_id in queries:
    relevant_docs[q_id] = [q_id]
 
 
matryoshka_evaluators = []
# Iterate over the different dimensions
for dim in matryoshka_dimensions:
    ir_evaluator = InformationRetrievalEvaluator(
        queries=queries,
        corpus=corpus,
        relevant_docs=relevant_docs,
        name=f"dim_{dim}",
        truncate_dim=dim,  # Truncate the embeddings to a certain dimension
        score_functions={"cosine": cos_sim},
    )
    matryoshka_evaluators.append(ir_evaluator)
 
# Create a sequential evaluator
evaluator = SequentialEvaluator(matryoshka_evaluators)

In [8]:
print(train_dataset)
print(test_dataset)
print(corpus_dataset)

Dataset({
    features: ['id', 'most_dissimilar_context', 'anchor', 'positive'],
    num_rows: 31837
})
Dataset({
    features: ['most_dissimilar_context', 'anchor', 'id', 'positive', 'contract_name'],
    num_rows: 1811
})
Dataset({
    features: ['id', 'most_dissimilar_context', 'anchor', 'positive', 'contract_name'],
    num_rows: 33648
})

In [10]:
#examine string lengths
def getinfo(dataset, column_name):
    lens=[]
    for s in dataset[column_name]:
        lens.append(len(s))
    print(f' Max length of {column_name}={max(lens)}')
    # print(f' Average length of {sum(lens)/len(lens)}')
    return lens

#get columns
# cols=list((dataset.features.keys()))
cols=['anchor', 'positive']
for c in cols:
    getinfo(test_dataset,c)

 Max length of anchor=2184
 Max length of positive=23327

In [8]:
#{'dim_768_cosine_accuracy@1': 0.046472751588097626, 'dim_768_cosine_accuracy@3': 0.13473754597124707, 'dim_768_cosine_accuracy@5': 0.21664994984954863, 'dim_768_cosine_accuracy@10': 0.379806084921431, 'dim_768_cosine_precision@1': 0.046472751588097626, 'dim_768_cosine_precision@3': 0.04491251532374902, 'dim_768_cosine_precision@5': 0.043329989969909735, 'dim_768_cosine_precision@10': 0.037980608492143096, 'dim_768_cosine_recall@1': 0.046472751588097626, 'dim_768_cosine_recall@3': 0.13473754597124707, 'dim_768_cosine_recall@5': 0.21664994984954863, 'dim_768_cosine_recall@10': 0.379806084921431, 'dim_768_cosine_ndcg@10': 0.18168960028685946, 'dim_768_cosine_mrr@10': 0.12241924185254166, 'dim_768_cosine_map@100': 0.13706205948940364, 'dim_512_cosine_accuracy@1': 0.03945168839852892, 'dim_512_cosine_accuracy@3': 0.12771648278167838, 'dim_512_cosine_accuracy@5': 0.20327649615513207, 'dim_512_cosine_accuracy@10': 0.38214643931795383, 'dim_512_cosine_precision@1': 0.03945168839852892, 'dim_512_cosine_precision@3': 0.04257216092722612, 'dim_512_cosine_precision@5': 0.04065529923102641, 'dim_512_cosine_precision@10': 0.03821464393179538, 'dim_512_cosine_recall@1': 0.03945168839852892, 'dim_512_cosine_recall@3': 0.12771648278167838, 'dim_512_cosine_recall@5': 0.20327649615513207, 'dim_512_cosine_recall@10': 0.38214643931795383, 'dim_512_cosine_ndcg@10': 0.17786461524839592, 'dim_512_cosine_mrr@10': 0.11693731989619656, 'dim_512_cosine_map@100': 0.13065774805339672, 'sequential_score': 0.13065774805339672}
# dim_768_cosine_ndcg@10: 0.18168960028685946
# dim_512_cosine_ndcg@10: 0.17786461524839592

In [11]:
# Evaluate the model
results = evaluator(model)
 
# # COMMENT IN for full results
# print(results)
 
# Print the main score
for dim in matryoshka_dimensions:
    key = f"dim_{dim}_cosine_ndcg@10"
    print
    print(f"{key}: {results[key]}")

dim_768_cosine_ndcg@10: 0.21829776813564813
dim_512_cosine_ndcg@10: 0.20800673495140842

In [12]:
from sentence_transformers import SentenceTransformerModelCardData, SentenceTransformer
 
# Hugging Face model ID: https://huggingface.co/BAAI/bge-base-en-v1.5
model_id = "BAAI/bge-base-en-v1.5"
 
# load model with SDPA for using Flash Attention 2
model = SentenceTransformer(
    model_id,
    device="cuda:0" if torch.cuda.is_available() else "cpu",
    model_kwargs={"attn_implementation": "sdpa"},
    model_card_data=SentenceTransformerModelCardData(
        language="en",
        license="apache-2.0",
        model_name="BGE base Financial Matryoshka",
    ),
)

/home/kperkins411/anaconda3/envs/p311/lib/python3.11/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [13]:
%%time
from sentence_transformers.losses import MatryoshkaLoss, MultipleNegativesRankingLoss
 
matryoshka_dimensions = [768, 512]  # Important: large to small
inner_train_loss = MultipleNegativesRankingLoss(model)
train_loss = MatryoshkaLoss(
    model, inner_train_loss, matryoshka_dims=matryoshka_dimensions
)

CPU times: user 163 μs, sys: 6 μs, total: 169 μs
Wall time: 191 μs

In [12]:
# !pip install transformers[torch]

In [14]:
%%time
from sentence_transformers import SentenceTransformerTrainingArguments
from sentence_transformers.training_args import BatchSamplers
 
# define training arguments
args = SentenceTransformerTrainingArguments(
    output_dir="bge-base-financial-matryoshka", # output directory and hugging face model ID
    num_train_epochs=4,                         # number of epochs
    per_device_train_batch_size=32,             # train batch size
    gradient_accumulation_steps=16,             # for a global batch size of 512
    per_device_eval_batch_size=16,              # evaluation batch size
    warmup_ratio=0.1,                           # warmup ratio
    learning_rate=2e-5,                         # learning rate, 2e-5 is a good value
    lr_scheduler_type="cosine",                 # use constant learning rate scheduler
    optim="adamw_torch_fused",                  # use fused adamw optimizer
    tf32=True,                                  # use tf32 precision
    bf16=True,                                  # use bf16 precision
    batch_sampler=BatchSamplers.NO_DUPLICATES,  # MultipleNegativesRankingLoss benefits from no duplicate samples in a batch
    eval_strategy="epoch",                      # evaluate after each epoch
    save_strategy="epoch",                      # save after each epoch
    logging_steps=10,                           # log every 10 steps
    save_total_limit=3,                         # save only the last 3 models
    load_best_model_at_end=True,                # load the best model when training ends
    metric_for_best_model="eval_dim_512_cosine_ndcg@10",  # Optimizing for the best ndcg@10 score for the 128 dimension
)

Currently using DataParallel (DP) for multi-gpu training, while DistributedDataParallel (DDP) is recommended for faster training. See https://sbert.net/docs/sentence_transformer/training/distributed.html for more information.

CPU times: user 10.9 ms, sys: 5.93 ms, total: 16.8 ms
Wall time: 178 ms

In [15]:
%%time
from sentence_transformers import SentenceTransformerTrainer
 
trainer = SentenceTransformerTrainer(
    model=model, # bg-base-en-v1
    args=args,  # training arguments
    train_dataset=train_dataset.select_columns(
        ["positive", "anchor"]
    ),  # training dataset
    loss=train_loss,
    evaluator=evaluator,
)

CPU times: user 7.87 s, sys: 1.56 s, total: 9.43 s
Wall time: 1.8 s

In [16]:
#liit to 1 GPU
device = torch.device("cuda:1") # to use GPU ID 1 only
trainer.args._n_gpu = 1

# Clear Memory

In [17]:
import torch, gc
gc.collect()
torch.cuda.empty_cache()

In [11]:
%%time

# start training, the model will be automatically saved to the hub and the output directory
trainer.train()
 
# save the best model
trainer.save_model()
 
# push model to hub
# trainer.model.push_to_hub("bge-base-financial-matryoshka")

CPU times: user 3h 20min 3s, sys: 5min 44s, total: 3h 25min 48s
Wall time: 11min 45s

In [15]:
%%time

# start training, the model will be automatically saved to the hub and the output directory
trainer.train()
 
# save the best model
trainer.save_model()
 
# push model to hub
trainer.model.push_to_hub("bge-base-financial-matryoshka")

HfHubHTTPError: 409 Client Error: Conflict for url: https://huggingface.co/api/repos/create (Request ID: Root=1-6677ac39-758952542a38df3739af16cd;907f71c8-f3de-44df-a774-f7af226f51d4)

You already created this model repo

In [12]:
%%time
from sentence_transformers import SentenceTransformer
 
fine_tuned_model = SentenceTransformer(
    args.output_dir, device="cuda:0" if torch.cuda.is_available() else "cpu"
)
# Evaluate the model
results = evaluator(fine_tuned_model)
 
# # COMMENT IN for full results
print(results)
 
# Print the main score
for dim in matryoshka_dimensions:
    key = f"dim_{dim}_cosine_ndcg@10"
    print(f"{key}: {results[key]}")

{'dim_768_cosine_accuracy@1': 0.05521811154058531, 'dim_768_cosine_accuracy@3': 0.18553285477636663, 'dim_768_cosine_accuracy@5': 0.2954168967421314, 'dim_768_cosine_accuracy@10': 0.5251242407509663, 'dim_768_cosine_precision@1': 0.05521811154058531, 'dim_768_cosine_precision@3': 0.06184428492545555, 'dim_768_cosine_precision@5': 0.059083379348426286, 'dim_768_cosine_precision@10': 0.052512424075096625, 'dim_768_cosine_recall@1': 0.05521811154058531, 'dim_768_cosine_recall@3': 0.18553285477636663, 'dim_768_cosine_recall@5': 0.2954168967421314, 'dim_768_cosine_recall@10': 0.5251242407509663, 'dim_768_cosine_ndcg@10': 0.2470760245619197, 'dim_768_cosine_mrr@10': 0.16377494675396373, 'dim_768_cosine_map@100': 0.18054194698024514, 'dim_512_cosine_accuracy@1': 0.059083379348426286, 'dim_512_cosine_accuracy@3': 0.19050248481501933, 'dim_512_cosine_accuracy@5': 0.2987299834345665, 'dim_512_cosine_accuracy@10': 0.5118718939812258, 'dim_512_cosine_precision@1': 0.059083379348426286, 'dim_512_cosine_precision@3': 0.06350082827167311, 'dim_512_cosine_precision@5': 0.0597459966869133, 'dim_512_cosine_precision@10': 0.051187189398122585, 'dim_512_cosine_recall@1': 0.059083379348426286, 'dim_512_cosine_recall@3': 0.19050248481501933, 'dim_512_cosine_recall@5': 0.2987299834345665, 'dim_512_cosine_recall@10': 0.5118718939812258, 'dim_512_cosine_ndcg@10': 0.24677257384258666, 'dim_512_cosine_mrr@10': 0.1669870193613979, 'dim_512_cosine_map@100': 0.1847682366863142, 'sequential_score': 0.1847682366863142}
dim_768_cosine_ndcg@10: 0.2470760245619197
dim_512_cosine_ndcg@10: 0.24677257384258666
CPU times: user 24min 55s, sys: 37.9 s, total: 25min 33s
Wall time: 33.3 s